# Generated by Django 4.2.30 on 2026-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse_payment_adaptor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='musetransactionlog',
            name='muse_txlog_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='musetransactionlog',
            name='muse_txlog_type_idx',
        ),
        migrations.RenameIndex(
            model_name='musetransactionlog',
            new_name='muse_Transa_benefit_7fe0de_idx',
            old_name='muse_txlog_code_type_idx',
        ),
        migrations.RenameIndex(
            model_name='musetransactionlog',
            new_name='muse_Transa_payroll_d4d94f_idx',
            old_name='muse_txlog_payroll_status_idx',
        ),
        migrations.RenameIndex(
            model_name='musetransactionlog',
            new_name='muse_Transa_created_dfdb2a_idx',
            old_name='muse_txlog_created_idx',
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='benefit_code',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='payroll_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('REJECTED', 'Rejected by Gateway')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('RECONCILIATION', 'Reconciliation')], db_index=True, max_length=20),
        ),
    ]
