# Generated by Django 4.2.30 on 2026-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse_payment_adaptor', '0002_remove_musetransactionlog_muse_txlog_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musetransactionlog',
            name='batch_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='musetransactionlog',
            name='direction',
            field=models.CharField(default='OUT', max_length=3),
        ),
        migrations.AddField(
            model_name='musetransactionlog',
            name='esb_request_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='musetransactionlog',
            name='item_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musetransactionlog',
            name='msg_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='musetransactionlog',
            name='paylist_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='benefit_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('REJECTED', 'Rejected by Gateway'), ('UNKNOWN', 'Outcome unknown'), ('NOT_SENT', 'Recorded without sending')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('BULK_PAYMENT', 'Bulk payment message'), ('RECONCILIATION', 'Reconciliation')], db_index=True, max_length=20),
        ),
    ]
