# Generated by Django 4.2.30 on 2026-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse_payment_adaptor', '0003_muse_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musetransactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('BULK_PAYMENT', 'Bulk payment message'), ('ACK', 'Acknowledgement'), ('RESPONSE', 'Batch response'), ('PAYMENT_STATUS', 'Payment status'), ('RECONCILIATION', 'Reconciliation')], db_index=True, max_length=20),
        ),
    ]
