# Generated by Django 4.2.30 on 2026-09-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse_payment_adaptor', '0004_inbound_types'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='musetransactionlog',
            name='muse_Transa_payroll_d4d94f_idx',
        ),
        migrations.RemoveField(
            model_name='musetransactionlog',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='musetransactionlog',
            name='fsp_name',
        ),
        migrations.RemoveField(
            model_name='musetransactionlog',
            name='fsp_type',
        ),
        migrations.RemoveField(
            model_name='musetransactionlog',
            name='payroll_id',
        ),
        migrations.AlterField(
            model_name='musetransactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('BULK_PAYMENT', 'Bulk payment message'), ('ACK', 'Acknowledgement'), ('RESPONSE', 'Batch response'), ('PAYMENT_STATUS', 'Payment status')], db_index=True, max_length=20),
        ),
    ]
